# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-aws:
    # Checks if CD passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Zip Release

        uses: TheDoctor0/zip-release@0.4.2
        with:
          # Filename for archive
          filename: lambda.zip # default is release.zip
          # Base path for archive files
          path: . # optional, default is .
          # Working directory before zipping
          directory: src # optional, default is .
          # List of excluded files / directories
          # exclusions: # optional, default is 
          # Tool to use for archiving
          # type: # optional, default is zip
      
      - name: ls
        run: ls src
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 File Upload
        # You may pin to the exact commit or the version.
        # uses: zdurham/s3-upload-github-action@dc0a62ddb6abe7cdbee3125659e32e729060f62a
        uses: zdurham/s3-upload-github-action@master
        with:
           args: --acl public-read
        env:
          FILE: src/lambda.zip
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          # S3_KEY: ${{ secrets.S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}





